// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"gin_graphql/app/models"
	"time"
)

type AuthResponse struct {
	AuthToken *AuthToken   `json:"authToken"`
	User      *models.User `json:"user"`
}

type AuthToken struct {
	AccessToken string    `json:"accessToken"`
	ExpiredAt   time.Time `json:"expiredAt"`
}

type MeetupFilter struct {
	Name *string `json:"name"`
}

type NewMeetup struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type RegisterInput struct {
	Account         string `json:"account"`
	Email           string `json:"email"`
	Password        string `json:"password"`
	ConfirmPassword string `json:"confirmPassword"`
}

type UpdateMeetup struct {
	Name        *string `json:"name"`
	Description *string `json:"description"`
}
